### ISSUE TITLE
having in issue were running your command to restart the server crashes

### ISSUE THREAD

**Issue by vannucci16** [ModdedMinecraft/MMCReboot-Sponge#17]
the server starts restarting but then stops half way leaving the server in a limbo state where it is neither up or down and nothing will happen till I manually restart then sometimes it won't come back up at all

[14:07:44] [Server thread/ERROR]: Exception stopping the serverjava.lang.RuntimeException: Attempt made to unload a world with dimension id [-1].at net.minecraftforge.common.DimensionManager.lambda$setWorld$0(DimensionManager.java:654) ~[DimensionManager.class:?]at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_112]at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) ~[DimensionManager.class:?]at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) ~[MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[fml-server-2.zip](https://github.com/ModdedMinecraft/MMCReboot-Sponge/files/1052854/fml-server-2.zip)
[latest.zip](https://github.com/ModdedMinecraft/MMCReboot-Sponge/files/1052856/latest.zip)

**Comment by leelawd** [comment]
The times in the FML log are from an earlier time than the latest.log 

But the error within the latest.log is not due to my plugin unfortunately. It does not handle the unloading of the dimensions itself and simply is just telling the server itself to run its own stopping mechanic.

i also noticed that
[14:27:27] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[14:27:27] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
show up twice.

maybe that has something to do with this error?
java.lang.RuntimeException: Attempt made to unload a world with dimension id [-1]. (Aka, Nether)

**Comment by vannucci16** [comment]
It's strange because I got the same error when using the restart button on my console but it didn't stop the restart from happening it only has an issue when I'm using your plug in to restart I shall test some more thank you for getting back to me

**Comment by vannucci16** [comment]
And yes I was aware that the times were different they were from two different instances of the crash
