### ISSUE TITLE
Server not restarting automatically on 1.12.2 API7

### ISSUE THREAD

**Issue by FiveEYZ** [ModdedMinecraft/MMCReboot-Sponge#22]
I recently updated to 1.12.2 and prior to the update i was using:
spongeforge-1.12.1-2444-7.0.0-BETA-2612
MMCReboot-2.0.4-API-5.1-6.X.jar

it was working all fine, but now im using:
MMCReboot-2.1.1-API-5.1-6.X
spongeforge-1.12.2-2503-7.0.0-BETA-2696

and server refuse to restart, im using Realtime in config
all warnings and announcements works but when its time to reboot this happens

at 12:00 it was configured to use a command:
```
[12:00:11] [Timer-51/INFO] [mmcreboot]: [MMCReboot] Running Command
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalStateException: CauseStackManager called from off main thread!
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:70)
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.event.SpongeCauseStackManager.pushCause(SpongeCauseStackManager.java:98)
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295)
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.moddedminecraft.mmcreboot.Main.useCommandOnRestart(Main.java:502)
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.moddedminecraft.mmcreboot.Tasks.ShutdownTask.run(ShutdownTask.java:40)
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.TimerThread.mainLoop(Unknown Source)
[12:00:11] [Timer-51/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.TimerThread.run(Unknown Source)
```

then i changed the config to reboot at 12:15 and to not use command:
```
[12:15:30] [Timer-71/INFO] [mmcreboot]: [MMCReboot] Restarting...
[12:15:30] [Timer-71/INFO] [mmcreboot]: [MMCReboot] Touching restart.txt at: H:\AMP\Instances\4-PreedCraft\Minecraft\.\plugins\mmcreboot\restart.txt
[12:15:30] [Timer-71/INFO] [mmcreboot]: [MMCReboot] Something went wrong while saving & stopping!
```

**Comment by leelawd** [comment]
When you updated the plugin, did you reset or change the config? I made a change to the command section, Just a speculation but if that is not in the correct list format, it might be preventing the plugin doing certain things.

**Comment by FiveEYZ** [comment]
first i tried with just the original config from when i used 2.0.4, but noticed the server never rebooted.

so i renamed it to generate a new one and after that didnt work i made this issue
well.. i renamed the folder so all files would be fresh

dont know how much it matters but here is my config, i changed line 3, 23 and 24
https://gist.github.com/FiveEYZ/0852af8df78a7dff679d0b5bcbbd3fb8

**Comment by ProsperCraft** [comment]
We are having the same problem with API 7, please update.

**Comment by FiveEYZ** [comment]
any news on this?

**Comment by leelawd** [comment]
I apologise for the length of time it took for this. I had been extremely busy for a while and have only just been able to sit down and sort out things like this.

https://ore.spongepowered.org/leelawd93/MMCReboot/versions/2.1.2

**Comment by PixelmonPRO** [comment]
Version 2.1.2
https://gist.github.com/PixelmonPRO/992379c908a1814550b0f4b252dfa9e3

**Comment by leelawd** [comment]
https://ore.spongepowered.org/leelawd93/MMCReboot/versions/2.1.3
